# Generated by Django 4.2.13 on 2024-06-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KPN', '0003_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000)),
                ('Rubles', models.FloatField()),
                ('KPNS', models.IntegerField()),
                ('user', models.ManyToManyField(to='KPN.user')),
            ],
        ),
    ]
