# Generated by Django 4.2.13 on 2024-06-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='user',
        ),
    ]
