# Generated by Django 4.2.13 on 2024-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currency_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='KPNS',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='currency',
            name='Rubles',
            field=models.CharField(max_length=100000),
        ),
    ]
