# Generated by Django 4.2.14 on 2024-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_currency_ratio_alter_currency_kpns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='KPNS',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='Rubles',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='ratio',
        ),
        migrations.AddField(
            model_name='currency',
            name='Amount',
            field=models.FloatField(default=0, max_length=10000000000000000000000000000),
            preserve_default=False,
        ),
    ]
