# Generated by Django 4.2.14 on 2024-08-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_remove_currency_description_remove_currency_kpns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Amount',
            field=models.FloatField(max_length=1000),
        ),
    ]
