# Generated by Django 4.2.14 on 2024-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_currency_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Amount',
            field=models.DecimalField(decimal_places=100000, max_digits=100000),
        ),
    ]
