# Generated by Django 4.2.14 on 2024-08-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_currency_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='Amount',
        ),
    ]
