# Generated by Django 4.2.14 on 2024-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_remove_currency_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='Amount',
            field=models.DecimalField(decimal_places=100000, default=0, max_digits=100000),
            preserve_default=False,
        ),
    ]
