# Generated by Django 4.2.14 on 2024-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_alter_currency_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Amount',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
