# Generated by Django 4.2.13 on 2024-06-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPN', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
