# Generated by Django 4.2.13 on 2024-06-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currency_user'),
        ('KPN', '0003_delete_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curency',
            field=models.ManyToManyField(to='currency.currency'),
        ),
    ]
