# Generated by Django 4.2.13 on 2024-06-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPN', '0004_user_curency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='KPNS',
            new_name='KPСS',
        ),
    ]
