# Generated by Django 4.2.13 on 2024-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPN', '0006_remove_user_curency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MONEYS',
            field=models.CharField(default='0', max_length=10000),
        ),
        migrations.AddField(
            model_name='user',
            name='MONEYTAP',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
