# Generated by Django 4.2.13 on 2024-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0002_remove_foreman_system_user'),
        ('KPN', '0007_user_moneys_user_moneytap'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foreman',
            field=models.ManyToManyField(to='foreman.foreman'),
        ),
    ]
