# Generated by Django 4.2.14 on 2024-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPN', '0009_user_is_foreman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='MONEYS',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MONEYTAP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foreman',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_foreman',
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='KPСS',
            field=models.FloatField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='Rubles',
            field=models.FloatField(max_length=100000),
        ),
    ]
