# Generated by Django 4.2.14 on 2024-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPN', '0010_remove_user_moneys_remove_user_moneytap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='KPСS',
            field=models.DecimalField(decimal_places=100, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='Rubles',
            field=models.DecimalField(decimal_places=100, max_digits=1000),
        ),
    ]
