# Generated by Django 4.2.14 on 2024-08-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPN', '0011_alter_user_kpсs_alter_user_rubles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='KPСS',
            new_name='KPCS',
        ),
    ]
