# Generated by Django 4.2.13 on 2024-06-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KPN', '0007_user_moneys_user_moneytap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPN.user')),
            ],
        ),
    ]
