# Generated by Django 4.2.13 on 2024-06-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreman',
            name='system_user',
        ),
    ]
