# Generated by Django 4.2.13 on 2024-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreman', '0002_remove_foreman_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreman',
            name='Telegram_ID',
            field=models.IntegerField(default=0),
        ),
    ]
